default_context:
  project_name: 'work-core-api'
  project_slug: 'workcore'
  domain_main: 'workcore.com'
  domain_staging: 'stag.workcore.com'
  docker_swarm_stack_name_main: 'workcore-com'
  docker_swarm_stack_name_staging: 'stag-workcore-com'
  secret_key: 'e2421b08d27a01ee8a9459c5cacf785989aede5f7261c7ab020ed58a49d8a621'
  first_superuser: 'admin@workcore.com'
  first_superuser_password: 'admin123'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.workcore.com", "https://stag.workcore.com", "https://workcore.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@workcore.com'
  postgres_password: 'admin123'
  pgadmin_default_user: 'admin@workcore.com'
  pgadmin_default_user_password: 'admin123'
  traefik_constraint_tag: 'workcore.com'
  traefik_constraint_tag_staging: 'stag.workcore.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin123'
  sentry_dsn: ''
  docker_image_prefix: 'wc'
  docker_image_backend: 'wcbackend'
  docker_image_celeryworker: 'wcceleryworker'
  docker_image_frontend: 'wcfrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
